# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d7f4419bb435969d61ae034f35ac4618ee598fec07a585807af8fd8585ee4e2c11c32ee1b8875a36ef28101122948bf3e54e9ab14ec2f3a66fdb84237910dae

test:
  secret_key_base: b4679b61019093622be36ee6e234236e3c08092635105c34fb6d8bd9b12d05bebe11bc6c8081daffd1e7fe4a773814cf0aebc05ad2d713eb26a6b27c8587fa20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
